apiVersion: v1
kind: Service
metadata:
  name: genraft-ai-backend
spec:
  type: ClusterIP
  ports:
    - port: 5003
      name: api
      targetPort: 5003
      protocol: TCP
  selector:
    app: genraft-ai-backend
