apiVersion: v1
kind: Service
metadata:
  name: genraft-ai-frontend
spec:
  type: ClusterIP
  ports:
    - port: 3000
      name: webui
      targetPort: 3000
      protocol: TCP
  selector:
    app: genraft-ai-frontend
